language: php

cache:
  directories:
    - vendor
    - bin
env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  include:
    - php: 7.4
      env:
        - COMPOSER_FLAGS='--prefer-lowest'
    - php: 7.4
    - php: 8.1

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.17.8-amd64.deb
  - sudo dpkg -i --force-confnew elasticsearch-7.17.8-amd64.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

before_script:
  - sleep 10 # for elasticsearch (from travis documentation)
  - composer update $COMPOSER_FLAGS

script: vendor/bin/phpunit
