version: '2.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: datasource-elastica-elasticsearch
    environment:
      - cluster.name=datasource-elastica
      - xpack.security.enabled=false
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
      - 9300:9300
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: datasource-elastica-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://datasource-elastica-elasticsearch:9200
      ELASTICSEARCH_HOSTS: '["http://datasource-elastica-elasticsearch:9200"]'